name: Terraform Validate
on:
  pull_request:
    branches: [main]
jobs:
  cli-validations:
    runs-on: ubuntu-latest
    name: Terraform cli validations
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.3.2
        with:
          terraform_wrapper: false

      - name: Terraform Format
        run: terraform fmt -check --recursive

      - name: Terraform Validate Examples
        working-directory: examples/complete
        run: |
          terraform init -backend=false
          terraform validate ./

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@v12.567.0
